// Generated by CoffeeScript 1.7.1
(function() {
  var bunyan, gateways, glob, log, service, _i, _len, _ref;

  bunyan = require('bunyan');

  glob = require('glob');

  gateways = require('./gateways');

  log = bunyan.createLogger({
    name: 'dollnet'
  });

  gateways.start(log);

  _ref = glob.sync('./services/*.js');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    service = _ref[_i];
    require(service).start(log, gateways);
  }

}).call(this);

//# sourceMappingURL=main.map
