// Generated by CoffeeScript 1.7.1
(function() {
  var shadowsocks, url;

  url = require('url');

  shadowsocks = {
    schema: 'ss',
    start: function(gateway, callback) {
      var gateway_uri, method, password, server, _ref;
      gateway_uri = url.parse(gateway);
      if (gateway_uri.auth == null) {
        gateway_uri = url.parse('ss://' + new Buffer(gateway.slice(5), 'base64').toString());
      }
      _ref = gateway_uri.auth.split(':', 2), method = _ref[0], password = _ref[1];
      server = require('shadowsocks').createServer(gateway_uri.hostname, gateway_uri.port, 0, password, method, 2000, '127.0.0.1');
      server.on("error", function(e) {
        return console.log(e);
      });
      return server.on('listening', function() {
        return callback("socks5://localhost:" + (server.address().port));
      });
    }
  };

  module.exports = shadowsocks;


  /*
    services:
      http: (uri, callback)->
        shttp.get "http://www.google.com/", callback
  
    speedtest_started_at = new Date()
        request
          url: 'https://www.google.com/',
          agent: new Socks5ClientHttpsAgent
            socksPort: local_port
        , (err, res)->
          if err
            console.log "#{node.id}: #{err}"
          else
            console.log "#{node.id}: SUCCESS in #{new Date() - speedtest_started_at} ms"
   */

}).call(this);

//# sourceMappingURL=shadowsocks.map
